/**
 * The shapes the queue/presence machine works with: persisted state, the
 * commands that change it, and the effects it asks the shell to perform.
 *
 * Nothing here executes. See ./reduce.ts for the transitions and ./views.ts for
 * what clients are shown.
 */

import type { AssignmentMode, CallEndReason, ServerMessage, VisitorStatus } from '../protocol'

// ─── State ───────────────────────────────────────────────────────────────────

export interface QueueEntry {
  /** queue_sessions.id — the durable record of this person's turn in line. */
  id: string
  visitorId: string
  firstName: string
  email: string | null
  company: string | null
  question: string | null
  siteId: string
  pageUrl: string
  pageTitle: string | null
  referrer: string | null
  joinedAt: number
  status: 'waiting' | 'invited'
  /** The agent inviting them, while status is 'invited'. */
  assignedTo: string | null
  /** Live socket present. False during the disconnect grace window. */
  connected: boolean
  /** When the last socket for this visitor closed; drives grace eviction. */
  disconnectedAt: number | null
}

export interface AgentState {
  id: string
  name: string
  /** What the agent last asked for. Status is derived from it plus reality. */
  intent: 'offline' | 'live' | 'paused'
  connections: number
  disconnectedAt: number | null
  liveSince: number | null
  /** The round-robin cursor: when this agent was last handed a visitor. 0 = never. */
  lastAssignedAt: number
}

export interface Invite {
  agentId: string
  visitorId: string
  queueEntryId: string
  callId: string
  issuedAt: number
  expiresAt: number
}

export interface CallRecord {
  callId: string
  /** Bearer secret the call page trades for RealtimeKit credentials. Never broadcast. */
  callSecret: string
  agentId: string
  agentName: string
  visitorId: string
  queueEntryId: string
  firstName: string
  siteId: string
  pageUrl: string
  question: string | null
  /**
   * The rest of the queue entry, kept so a visitor who is put back in line —
   * provisioning failed, the agent went offline — returns with their details
   * and their ORIGINAL place in time, not a fresh join.
   */
  email: string | null
  company: string | null
  pageTitle: string | null
  referrer: string | null
  joinedAt: number
  /** Null until the RealtimeKit meeting has been created. */
  meetingId: string | null
  status: 'provisioning' | 'connecting' | 'in_call'
  /** When the agent accepted (or was assigned). The invite countdown runs from here. */
  startedAt: number
  /** When the visitor accepted the invitation; starts the connect timeout. */
  acceptedAt: number | null
  /** When both sides were actually in the media room. Metrics use this. */
  connectedAt: number | null
  hostPresent: boolean
  visitorPresent: boolean
  hostLeftAt: number | null
  visitorLeftAt: number | null
}

export interface RoomState {
  /** Shape version. The DO discards a persisted state of any other shape. */
  version: 2
  orgId: string
  agents: Record<string, AgentState>
  queue: QueueEntry[]
  /** Keyed by agentId. */
  invites: Record<string, Invite>
  /** Keyed by agentId. */
  calls: Record<string, CallRecord>
  /** Durations in seconds of recently *connected* calls; drives the wait estimate. */
  recentDurations: number[]
  assignment: AssignmentMode
  /**
   * Until when automatic assignment is paused after a provisioning failure.
   * A failure to create a meeting is a system failure, not a visitor's, and
   * re-inviting immediately is a hot loop against a broken dependency — it
   * once took a Worker down. Manual accepts are unaffected. Null when clear.
   */
  provisionHoldUntil: number | null
  /** Ring buffer of applied commandIds — the idempotency guard. */
  recentCommandIds: string[]
}

export function initialState(orgId: string, assignment: AssignmentMode = 'auto'): RoomState {
  return {
    version: 2,
    orgId,
    agents: {},
    queue: [],
    invites: {},
    calls: {},
    recentDurations: [],
    assignment,
    provisionHoldUntil: null,
    recentCommandIds: []
  }
}

/** True if a persisted blob is a state this reducer understands. */
export function isCurrentState(value: unknown): value is RoomState {
  return typeof value === 'object' && value !== null && (value as { version?: unknown }).version === 2
}

// ─── Commands ────────────────────────────────────────────────────────────────

/** Fresh ids the reducer may consume. Generated by the caller; the reducer stays pure. */
export interface Ids {
  queueEntryId: string
  callId: string
  callSecret: string
}

export type Command =
  /** `connections` is the true socket count when the caller knows it; otherwise one is added. */
  | { t: 'HOST_CONNECT'; now: number; agentId: string; name: string; connections?: number }
  | { t: 'HOST_DISCONNECT'; now: number; agentId: string; remaining: number }
  | { t: 'HOST_GO_LIVE'; now: number; commandId: string; agentId: string; ids: Ids[] }
  | { t: 'HOST_GO_OFFLINE'; now: number; commandId: string; agentId: string; ids: Ids[] }
  | { t: 'HOST_PAUSE'; now: number; commandId: string; agentId: string }
  | { t: 'HOST_RESUME'; now: number; commandId: string; agentId: string; ids: Ids[] }
  | { t: 'HOST_SET_ASSIGNMENT'; now: number; commandId: string; mode: AssignmentMode; ids: Ids[] }
  | { t: 'VISITOR_CONNECT'; now: number; visitorId: string }
  | { t: 'VISITOR_DISCONNECT'; now: number; visitorId: string; remaining: number }
  | {
      t: 'QUEUE_JOIN'
      now: number
      commandId: string
      visitorId: string
      queueEntryId: string
      firstName: string
      email: string | null
      company: string | null
      question: string | null
      siteId: string
      pageUrl: string
      pageTitle: string | null
      referrer: string | null
      ids: Ids[]
    }
  | { t: 'QUEUE_LEAVE'; now: number; commandId: string; visitorId: string; ids: Ids[] }
  | { t: 'ACCEPT_NEXT'; now: number; commandId: string; agentId: string; ids: Ids[] }
  | { t: 'ACCEPT_VISITOR'; now: number; commandId: string; agentId: string; visitorId: string; ids: Ids[] }
  | { t: 'DECLINE_VISITOR'; now: number; commandId: string; agentId: string; visitorId: string; ids: Ids[] }
  | { t: 'VISITOR_ACCEPT_INVITE'; now: number; commandId: string; visitorId: string }
  | { t: 'VISITOR_DECLINE_INVITE'; now: number; commandId: string; visitorId: string; ids: Ids[] }
  | { t: 'CALL_PROVISIONED'; now: number; callId: string; meetingId: string }
  | { t: 'CALL_PROVISION_FAILED'; now: number; callId: string; error: string; ids: Ids[] }
  | { t: 'MEDIA_JOINED'; now: number; callId: string; who: 'host' | 'visitor' }
  | { t: 'MEDIA_LEFT'; now: number; callId: string; who: 'host' | 'visitor' }
  | { t: 'CALL_END'; now: number; commandId: string; callId: string; reason: CallEndReason; ids: Ids[] }
  /** Alarm. Applies every deadline that has passed; safe to call at any time. */
  | { t: 'TICK'; now: number; ids: Ids[] }

// ─── Effects ─────────────────────────────────────────────────────────────────

export type DbOp =
  | { t: 'queue_session_insert'; entry: QueueEntry }
  | { t: 'queue_session_status'; id: string; status: VisitorStatus; at: number; agentId?: string }
  | {
      t: 'call_start'
      callId: string
      agentId: string
      visitorId: string
      queueEntryId: string
      siteId: string
      meetingId: string | null
      at: number
    }
  | { t: 'call_end'; callId: string; at: number; durationSeconds: number; reason: CallEndReason }

export type AnalyticsName =
  | 'queue_joined'
  | 'queue_left'
  | 'call_invited'
  | 'call_invite_accepted'
  | 'call_invite_declined'
  | 'call_invite_expired'
  | 'call_started'
  | 'call_completed'

export type Effect =
  | { k: 'send_visitor'; visitorId: string; message: ServerMessage }
  | { k: 'send_agent'; agentId: string; message: ServerMessage }
  /** Every agent's dashboard. */
  | { k: 'send_agents'; message: ServerMessage }
  /** Every socket: widgets, waiting visitors and dashboards. */
  | { k: 'broadcast'; message: ServerMessage }
  | { k: 'provision_call'; callId: string; agentId: string; agentName: string; visitorId: string; firstName: string }
  /** Best-effort RealtimeKit teardown. Never blocks a state transition. */
  | { k: 'release_call'; callId: string; meetingId: string | null }
  | { k: 'db'; op: DbOp }
  | {
      k: 'analytics'
      name: AnalyticsName
      siteId: string | null
      visitorId: string | null
      agentId: string | null
      props?: Record<string, unknown>
    }

export interface Result {
  state: RoomState
  effects: Effect[]
}
