/**
 * Bundles the three browser entry points into src/generated/, where the Worker
 * imports them as text (the `Text` module rule in wrangler.jsonc) and serves them
 * with cache headers of its own choosing.
 *
 * Why a build step at all, for a project that otherwise avoids them: the widget,
 * the dashboard and the call page all speak the protocol defined in
 * src/shared/protocol.ts, and sharing those types across the wire boundary is
 * what stops a renamed field from becoming a runtime mystery. esbuild is the
 * smallest thing that allows it.
 *
 * Output is checked for size, because widget.js loads on every page view of every
 * embedding site and "lightweight" has to mean a number somebody notices when it
 * stops being true.
 */

import { build } from 'esbuild'
import { mkdir, stat, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const EOL = String.fromCharCode(10)
const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const outDir = join(root, 'src', 'generated')

/** Budgets in bytes of minified output. Exceeding one fails the build. */
const ENTRIES = [
  { name: 'widget', entry: 'client/widget/index.ts', budget: 52_000 },
  // Raised from 40k when the dashboard was split into modules: the boundaries
  // cost ~1 KB and bought a file per tab.
  { name: 'host', entry: 'client/host/index.ts', budget: 42_000 },
  { name: 'call', entry: 'client/call/index.ts', budget: 30_000 }
]

await mkdir(outDir, { recursive: true })

let failed = false

for (const { name, entry, budget } of ENTRIES) {
  const outfile = join(outDir, `${name}.js`)

  await build({
    entryPoints: [join(root, entry)],
    outfile,
    bundle: true,
    format: 'iife',
    // Baseline chosen to cover every browser the README commits to testing —
    // notably Safari 15, which is still the floor on older iPads.
    target: ['es2020', 'safari15', 'chrome90', 'firefox90', 'edge90'],
    platform: 'browser',
    minify: true,
    sourcemap: false,
    legalComments: 'none',
    logLevel: 'warning'
  })

  // The Worker imports this as text (the `Text` module rule in wrangler.jsonc),
  // so it needs a declaration or the import lands as `any`. Emitted here rather
  // than committed, because the .js it describes is not committed either.
  await writeFile(
    join(outDir, `${name}.d.ts`),
    ['declare const source: string', 'export default source', ''].join(EOL)
  )

  const { size } = await stat(outfile)
  const overBudget = size > budget
  if (overBudget) failed = true
  const kb = (size / 1024).toFixed(1)
  console.log(
    `${overBudget ? 'FAIL' : ' ok '}  ${name.padEnd(7)} ${kb.padStart(6)} KB  (budget ${(budget / 1024).toFixed(0)} KB)`
  )
}

// The Text module rule matches **/generated/*.js, so a stray non-bundle file in
// here would be served as a client asset. A README in the folder makes it obvious
// to anyone who opens it that nothing in here is hand-written.
await writeFile(
  join(outDir, 'README.txt'),
  'Generated by scripts/build-client.mjs. Do not edit; do not commit. Run `npm run build:client`.\n'
)

if (failed) {
  console.error('\nA client bundle exceeded its size budget. Trim it, or raise the budget deliberately.')
  process.exit(1)
}
